/**
 * PAINEL EXECUTIVO DE PROJETOS - DADOS INICIAIS
 * Fonte: Painel-de-Projetos.xlsx (Aba única: Projetos)
 * Atualizado em: 02/10/2026
 */

window.PANEL_DATA = {
  "metadata": {
    "title": "PAINEL EXECUTIVO DE PROJETOS",
    "sourceFile": "Painel-de-Projetos.xlsx",
    "generatedAt": "2026-10-02T13:07:04.399Z",
    "referenceDate": "02/10/2026"
  },
  "projetos": [
    {
      "ID Projeto": "PRJ001",
      "Projeto": "FOCUS",
      "Portaria": "Portaria DETRAN-SP Nº 2.889, DE 25 DE ABRIL DE 2024",
      "GP": "Isabella Monteiro",
      "Área": "DFT",
      "Status": "Em andamento",
      "Situação": "Atenção",
      "Justificativa da Situação": "Mudança de estratégia : \r\nDecisão de entrar na licitação da PRF para aquisição das câmeras corporais.\r\nDependência de licitação a ser realizada por outro órgão.",
      "Período da última semana": "28/09/2026 a 02/10/2026",
      "O que foi feito na última semana": "Nenhuma realização relevante registrada no período.\r\n",
      "% Execução": "79",
      "Data Início": "45407",
      "Data Fim Planejada": "45838",
      "Data Fim Atual": "46435",
      "Data Última RAP": "46283",
      "Últimas Atualizações": "Decisão de entrar na licitação da PRF para aquisição das câmeras corporais",
      "Próximos Passos": "",
      "Pontos de Atenção": "Aguardando licitação da PRF\r\nImplantação dos equipamentros",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "Atraso na licitação da PRF",
      "Escopo": "Estudar e implementar solução de monitoramento audiovisual da atuação do Departamento Estadual de Trânsito do Estado de São Paulo (DETRAN-SP).",
      "Objetivos Estratégicos": "Adotar as melhores práticas de transparência ativa, de acesso à informação e de proteção de dados\r\nAssegurar a qualidade dos serviços delegados com foco na excelência operacional\r\nCuidar das pessoas e valorizar o desempenho e o mérito\r\nEmpregar soluções tecnológicas inovadoras para alavancar os resultados\r\nFortalecer a atuação e a cooperação com os demais órgãos de trânsito e segurança pública\r\nOtimizar a fiscalização com foco na promoção da segurança e da eficiência\r\nPromover a cultura de integridade e auditoria permanente, combatendo com agilidade os desvios e a corrupção\r\nPromover a segurança no trânsito e reduzir os indicadores de óbitos e feridos em sinistros",
      "% Consumo Prazo": "100"
    },
    {
      "ID Projeto": "PRJ002",
      "Projeto": "ASIMOV",
      "Portaria": "Portaria DETRAN-SP nº 5.561, de 20 de setembro de 2024",
      "GP": "PRODESP",
      "Área": "DTI",
      "Status": "Em andamento",
      "Situação": "Saudável",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2027",
      "O que foi feito na última semana": "",
      "% Execução": "73",
      "Data Início": "45555",
      "Data Fim Planejada": "46370",
      "Data Fim Atual": "46377",
      "Data Última RAP": "46286",
      "Últimas Atualizações": "Após apresentação do Protótipo Renovação de CNH, ajustando os requisitos funcionais e Protótipo\r\nContinuando QA e homologação Portal do cidadão\r\nCSM homologado 27/08\r\nDesenvolvimento Live 2.0 com previsão de implantação para 03/11\r\nEntregeue MVP, com os seguintes serviços: Licenciamento, Pesquisa de Peças, Consulta Débitos e Restrições, Pagamento de Vistorias e TDV (todas)\r\nPlataforma de vistorias em Homologações com Integradoras e Auditoras em andamento\r\n",
      "Próximos Passos": "Disponibilizar nova versão renovação de CNH para validação da área de negócio\r\nDTI, na entrega Live 2.0, está fazendo a manuntenção do SISPL com previsão de implantação da API para 24/11\r\nHomologação até 01/09 app Serviços CSM\r\nPlataforma de vistorias em Homologações com Integradoras e Auditoras seguem em validação\r\nPortal do Cidadão QA e Homologação\r\nProgramar subida em produção app Serviços CSM",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "\r\nPlanejar a implementação e gerir a equipe de fornecedores para desenvolvimento de produtos digitais, para o Departamento Estadual de Trânsito do Estado de São Paulo (DETRAN-SP), utilizando modelos de inteligência artificial generativa e linguagem de grande escala.",
      "Objetivos Estratégicos": "Otimizar a experiência e a satisfação do usuário com o atendimento\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nComunicar com foco nos serviços, na prestação de contas e na construção da marca\r\nAdotar as melhores práticas de transparência ativa, acesso à informação e proteção de dados\r\nEmpregar soluções tecnológicas inovadoras para alavancar os resultados\r\n",
      "% Consumo Prazo": "82"
    },
    {
      "ID Projeto": "PRJ003",
      "Projeto": "SIAUT",
      "Portaria": "Portaria DETRAN-SP nº 4.830, de 30 de julho de 2024",
      "GP": "Cyntia Tiemi Nihy",
      "Área": "DFT",
      "Status": "Em andamento",
      "Situação": "Atenção",
      "Justificativa da Situação": "Projeto paralizado aguardando aprovação da etapa 4 pela Presidência\r\nDevido a férias do P.O. do projeto essa aprovação só ocorrerá após 13/10/2026",
      "Período da última semana": "28/09/2026 a 02/10/2028",
      "O que foi feito na última semana": "Nenhuma realização relevante registrada no período.\r\n",
      "% Execução": "92",
      "Data Início": "45511",
      "Data Fim Planejada": "45699",
      "Data Fim Atual": "46421",
      "Data Última RAP": "46296",
      "Últimas Atualizações": "Etapa 3 - concluída em 07/08/2026\r\nEtapa 4 definida pela DFT",
      "Próximos Passos": "\r\nEtapa 4 -aprovação da presidência\r\nEtapa 4 - início - requisitos\r\n",
      "Pontos de Atenção": "Aprovação  da etapa 4 - apenas após 13/10/2026, devido as férias do P.O. do projeto \r\n",
      "Impedimentos": "",
      "Pendências": "Definição da etapa 4 pela DFT",
      "Riscos": "",
      "Escopo": "O Projeto SIAUT tem por objetivo operacionalizar a lavratura de autuações e a aplicação das respectivas penalidades administrativas oriunda as infrações administrativas conhecidas como \"multas de balcão\", de competência do DETRAN-SP, que serão implantadas através de 04 (quatro) ETAPAS.\r\nETAPA1 (MULTAS ART. 165-D)\r\nETAPA2 (MULTAS ARTS.233 e 257, § 8º - NIC)\r\nETAPA3 (MULTAS ARTS. 162, 163 ou 164)\r\nETAPA4 (MULTAS ARTS. 240, 241, 242 e 243)",
      "Objetivos Estratégicos": "Implementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nOtimizar a fiscalização com foco na promoção da segurança e da eficiência\r\nPromover a segurança no trânsito e reduzir os indicadores de óbitos e feridos em sinistros",
      "% Consumo Prazo": "100"
    },
    {
      "ID Projeto": "PRJ004",
      "Projeto": "HABILITA-SP",
      "Portaria": "Portaria DETRAN-SP nº 49, de 22 de janeiro de 2025",
      "GP": "Priscilla Elias e Silva",
      "Área": "AEPE",
      "Status": "Em andamento",
      "Situação": "Atenção",
      "Justificativa da Situação": "Demora no processo de contratação pela área de infraestrutura.\r\nDesenhos técnicos necessários para contratação disponibilizados desde julho/2026.\r\n",
      "Período da última semana": "28/09/2026 a 02/10/2029",
      "O que foi feito na última semana": "",
      "% Execução": "53",
      "Data Início": "45659",
      "Data Fim Planejada": "46045",
      "Data Fim Atual": "",
      "Data Última RAP": "46287",
      "Últimas Atualizações": "Consolidação da Estaiadinha como projeto-piloto e referência técnica do Habilita SP;\r\nDesenvolvimento das definições de layout, fluxos, materialidade e aplicabilidade do conceito;\r\nConclusão e encaminhamento dos desenhos técnicos à Infraestrutura em julho/2026; Processo encaminhado para continuidade das etapas necessárias à contratação de projetos, obra e serviços para implantação da unidade",
      "Próximos Passos": "Prosseguimento, pela área de Infraestrutura, dos procedimentos necessários para contratação e implantação da unidade, contemplando os projetos e serviços necessários à execução da obra.\r\n \r\nParalelamente, as definições consolidadas no projeto-piloto deverão subsidiar a padronização e replicabilidade do Habilita SP, com as devidas adequações às características e necessidades de cada futura unidade.",
      "Pontos de Atenção": "Necessidade de acompanhamento do andamento da contratação pela Infraestrutura, considerando que os desenhos técnicos estão disponibilizados desde julho/2026.\r\n \r\nPor se tratar do projeto-piloto, eventuais ajustes identificados durante as etapas de projeto executivo e implantação deverão ser avaliados quanto ao seu impacto no padrão a ser replicado nas demais unidades do Habilita SP.",
      "Impedimentos": "",
      "Pendências": "Cronograma com estimativa do prazo final",
      "Riscos": "Risco de impacto no cronograma de implantação, caso haja prolongamento das etapas de contratação dos projetos, obra e serviços.\r\nConsiderando o caráter piloto da Estaiadinha, eventual atraso também poderá repercutir na validação prática das soluções e na consolidação do padrão para expansão do Habilita SP.",
      "Escopo": "Desenvolver e implementar, no âmbito do Estado de São Paulo, as localidades e instalações de realização dos exames práticos de direção veicular, com fundamento no artigo 12, da Resolução CONTRAN nº 789, 18 de junho de 2020, promovendo a formação responsável de condutores e contribuindo para a segurança viária, por meio de processos íntegros e eficientes, atendimento de excelência e infraestrutura de alta qualidade.",
      "Objetivos Estratégicos": "Adotar as melhores práticas de transparência ativa, de acesso à informação e de proteção de dados\r\nAperfeiçoar a estrutura organizacional e a qualificação do atendimento\r\nAssegurar a qualidade dos serviços delegados com foco na excelência operacional\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nOtimizar a alocação e modernização dos equipamentos e da infraestrutura\r\nOtimizar a experiência e a satisfação do usuário com o atendimento\r\nGarantir a qualidade dos serviços delegados, com foco na excelência operacional\r\nPromover a cultura de integridade e auditoria permanente, combatendo com agilidade os desvios e a corrupção",
      "% Consumo Prazo": "100"
    },
    {
      "ID Projeto": "PRJ005",
      "Projeto": "JORNADA DO CIDADÃO ",
      "Portaria": "",
      "GP": "Lincon Santos",
      "Área": "AEGE",
      "Status": "Em andamento",
      "Situação": "Saudável",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2030",
      "O que foi feito na última semana": "Reavaliação do trabalho pela AME, com ajuste no foco da entrega e na resolução do To-be",
      "% Execução": "88",
      "Data Início": "45901",
      "Data Fim Planejada": "46351",
      "Data Fim Atual": "46351",
      "Data Última RAP": "46286",
      "Últimas Atualizações": "Todas jornadas finalizadas",
      "Próximos Passos": "Aguardando validação AME\r\nAnalistas revisando todas as jornadas",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "Validação da jornadas",
      "Riscos": "",
      "Escopo": "Mapeamento de Jornadas, para levantamento de dores e propostas de melhorias com foco no cidadão",
      "Objetivos Estratégicos": "Disseminar a cultura de inovação, a gestão de projetos e processos\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nOtimizar a experiência e a satisfação do usuário com o atendimento",
      "% Consumo Prazo": "89"
    },
    {
      "ID Projeto": "PRJ006",
      "Projeto": "ITSM-2026",
      "Portaria": "",
      "GP": "Arturo Sangiovani",
      "Área": "DTI",
      "Status": "Em andamento",
      "Situação": "Atenção",
      "Justificativa da Situação": "O projeto original contemplava os módulos ITSM, ITAM e ITOM\r\nAtualmente os módulos ITAM e ITOM estão \"congelados\" e os esforços estão concentrados apenas no ITSM",
      "Período da última semana": "28/09/2026 a 02/10/2031",
      "O que foi feito na última semana": "",
      "% Execução": "66",
      "Data Início": "45938",
      "Data Fim Planejada": "46383",
      "Data Fim Atual": "46365",
      "Data Última RAP": "46286",
      "Últimas Atualizações": "Desenvolvidos os catálogos de serviço das divisões de Visualização, Preparação de Dados e Proteção de Dados\r\nSolicitado desevolvimento da tela inicial com características do Detran",
      "Próximos Passos": "Catálogo de Proteção de Dados - 05/10/2026\r\nCatálogo de Auditoria Forense Digital - 04/11/2026\r\nCatálogoo de Segurança da Informação - 10/11/2026\r\nCatálogo de Gestão e Monitoramento - 03/12/2026\r\nCatálogo de Monitoramento de Incidentes - 09/12/2026\r\n",
      "Pontos de Atenção": "Módulos ITAM e ITOM estão \"congelados\" e os esforços estão concentrados apenas no ITSM",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Implantação e a operacionalização de um sistema integrado de gestão de ativos, de serviços e de operações de Tecnologia da Informação (TI) no âmbito do DETRAN-SP visando a otimização e o controle dos processos relacionados à gestão do ciclo de vida dos ativos de TI, à prestação de serviços de TI e à eficiência operacional dos processos de TI.",
      "Objetivos Estratégicos": "Empregar soluções tecnológicas inovadoras para alavancar os resultados\r\nAperfeiçoar a estrutura organizacional e a qualificação do atendimento\r\nOtimizar a alocação e modernização dos equipamentos e da infraestrutura\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nImplementar gestão de performance e subsidiar as decisões com evidências\r\nReduzir o custo dos serviços e contribuir para a competitividade e a prosperidade do Estado de São Paulo\r\n\r\n\r\n",
      "% Consumo Prazo": "82"
    },
    {
      "ID Projeto": "PRJ007",
      "Projeto": "PLATAFORMA ESTADUAL DE VISTORIA",
      "Portaria": "Portaria DETRAN-SP nº 5.561, de 20 de setembro de 2024",
      "GP": "Arturo Sangiovani",
      "Área": "DVA",
      "Status": "Em andamento",
      "Situação": "Saudável",
      "Justificativa da Situação": "Projeto segue como planejado\r\nImplantação gradual:\r\nClassificação de Monta - 01/10/2026\r\nMera identificação - 16/10/2026\r\nCompra e Venda de Veículos - 01/11/2026",
      "Período da última semana": "28/09/2026 a 02/10/2032",
      "O que foi feito na última semana": "Homologação e implantação da Classificação de Monta -01/10/2026",
      "% Execução": "93",
      "Data Início": "45988",
      "Data Fim Planejada": "46204",
      "Data Fim Atual": "46379",
      "Data Última RAP": "46293",
      "Últimas Atualizações": "Homologações com Integradoras e Auditoras em andamento",
      "Próximos Passos": "Implantação Classificação de Monta - 01/10/2026\r\nImplantação Mera identificação - 16/10/2026\r\nImplantação Compra e Venda de Veículos - 01/11/2026\r\nOperação Assistida até 23/12/2026",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Desenvolvimento e implantação da jornada de pagamento digital das vistorias veiculares no Portal Detran-SP, com integração ao ambiente financeiro do Banco do Brasil e à Plataforma\r\nEstadual de Veículos, conforme as especificações técnicas e requisitos funcionais validados pela Diretoria de Veículos Automotores.\r\nO serviço tem por objetivo viabilizar o recolhimento eletrônico das taxas de vistoria por meio de PIX, dispensando login prévio, com rastreabilidade integral das transações, integração automática com os sistemas de vistoria e restituição automatizada de valores.",
      "Objetivos Estratégicos": "Implementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nPromover a cultura de integridade e auditoria permanente, combatendo com agilidade os desvios e a corrupção\r\nAdotar as melhores práticas de transparência ativa, acesso à informação e proteção de dados\r\nAssegurar a qualidade dos serviços delegados com foco na excelência operacional\r\n\r\n",
      "% Consumo Prazo": "100"
    },
    {
      "ID Projeto": "PRJ008",
      "Projeto": "RST",
      "Portaria": "",
      "GP": "BeSolution",
      "Área": "DSV",
      "Status": "Em andamento",
      "Situação": "Atenção",
      "Justificativa da Situação": "Na homologação da V2 e V3 do aplicativo foram encontrados mais de 80 problemas\r\nA data prevista inicialmente de 25/09/2026 não foi atingida e não há ainda previsão para o fim do projeto",
      "Período da última semana": "28/09/2026 a 02/10/2033",
      "O que foi feito na última semana": "Correção de BUGs da V2 e V3",
      "% Execução": "99",
      "Data Início": "46042",
      "Data Fim Planejada": "46185",
      "Data Fim Atual": "",
      "Data Última RAP": "46288",
      "Últimas Atualizações": "Correção de Bugs da V3 -30/09/2026 (54 itens)\r\n\r\n",
      "Próximos Passos": "Homologação (correção dos 54 itens) - 06/10/2026\r\nSubida em produção -  07/10/2026\r\nCorreção de demais itens da V3 - 12/10/2026",
      "Pontos de Atenção": "O módulo Admin será entregue com a V4\r\nO  ininício da versão V4 está condicionada ao término da V3.\r\nRefinamento dos requisitos - início previsto 13/10/2026",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "Possível revisão de escopo - impacto no cronograma\r\nNão há previsão para o término do projeto",
      "Escopo": "O RST (Registro de Sinistro de Trânsito) é um sistema digital inovador desenvolvido para modernizar o processo de registro e acompanhamento de acidentes de trânsito.\r\nO projeto tem como foco usabilidade, automação inteligente e integração com fontes oficiais, operando totalmente em nuvem e com arquitetura escalável, responsiva e segura.\r\nO sistema foi construído sobre bases técnicas e operacionais que garantem segurança, desempenho e conformidade.\r\nFoco em entregar App com módulo RST, sendo aplicativo único para todos órgãos de trânsito, com transcrição IA para agente de trânsito/GCM para reportar notificações e integração monta Infosiga.",
      "Objetivos Estratégicos": "Fortalecer a atuação e a cooperação com os demais órgãos de trânsito e segurança pública\r\nPromover a segurança no trânsito e reduzir os indicadores de óbitos e feridos em sinistros\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nOtimizar a fiscalização com foco na promoção da segurança e da eficiência\r\nSer a plataforma de integração, informação e cooperação para o trânsito\r\nSubsidiar políticas públicas com foco em resultados concretos e mensuráveis\r\nAmpliar a disponibilidade, a eficiência e a acessibilidade de todos os serviços a todas as pessoas\r\nAutomatizar os processos com emprego de inteligência artificial e aprendizagem de máquinas \r\n",
      "% Consumo Prazo": "100"
    },
    {
      "ID Projeto": "PRJ009",
      "Projeto": "POLESTAR - MSFT",
      "Portaria": "",
      "GP": "Artur Giannini",
      "Área": "DGR",
      "Status": "Em andamento",
      "Situação": "Problema",
      "Justificativa da Situação": "Projeto apresenta significativo atraso e não há previsão para o término:\r\nAgente Q&amp;A da Wiki (\"Isa\") -Integração com o portal - Best - sem previsão\r\nAgente Revisor de Conteúdo da wiki - Microsoft - sem previsão\r\nAgente Revisor de Conteúdo da wiki - Integração com o portal - Best - sem previsão",
      "Período da última semana": "28/09/2026 a 02/10/2034",
      "O que foi feito na última semana": "Implantação de melhorias no Sistema de Atendimento",
      "% Execução": "50",
      "Data Início": "46111",
      "Data Fim Planejada": "46187",
      "Data Fim Atual": "",
      "Data Última RAP": "46282",
      "Últimas Atualizações": "Base de Conhecimento - entregue 14/06/2026\r\nSistema de Atendimento - entregue 14/06/2026\r\nBase de Conhecimento - correções - entregue 21/09/2026\r\n",
      "Próximos Passos": "Sistema de atendimento - melhorias - 30/09/2026\r\nAgente OCR de Documentos de Credenciamento - integração com o portal - 22/10/2026\r\nAgente Q&amp;A da Wiki (\"Isa\") - Microsoft - 06/11/2026",
      "Pontos de Atenção": "Agente Q&amp;A da Wiki (\"Isa\") -Integração com o portal - Best - sem previsão\r\nAgente Revisor de Conteúdo da wiki - Microsoft - sem previsão\r\nAgente Revisor de Conteúdo da wiki - Integração com o portal - Best - sem previsão\r\n",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "A falta de um cronograma definido pela MIcrosoft, e a necessidade de  integração com o portal a cargo da Best sinalizam atrasos significativos para esse projeto.",
      "Escopo": "Base de Conhecimento\r\nSistema de Atendimento\r\nAgente OCR de documentos de credenciamento\r\nAgente Q&amp;A da Wiki (\"Isa\")\r\nAgente Revisor de conteúdo da Wiki\r\n",
      "Objetivos Estratégicos": "Ampliar a disponibilidade, a eficiência e a acessibilidade digital de todos os serviços a todas as pessoas\r\nAperfeiçoar a estrutura organizacional e a qualificação do atendimento\r\nAssegurar a qualidade dos serviços delegados com foco na excelência operacional\r\nAutomatizar os processos com emprego de inteligência artificial e aprendizagem de máquinas\r\nEmpregar soluções tecnológicas inovadoras para alavancar os resultados\r\nEstruturar o controle interno e a gestão de riscos com as melhores práticas de \"compliance\" (conformidade)\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nImplementar rede colaborativa de parceiros em prol da segurança de todos\r\nOtimizar a experiência e a satisfação do usuário com o atendimento\r\nReduzir o custo dos serviços e contribuir para a competitividade e a prosperidade do Estado de São Paulo",
      "% Consumo Prazo": "100"
    },
    {
      "ID Projeto": "PRJ010",
      "Projeto": "CONCURSO PÚBLICO",
      "Portaria": "",
      "GP": "Sérgio Araújo",
      "Área": "DSV",
      "Status": "Em andamento",
      "Situação": "Saudável",
      "Justificativa da Situação": "Projeto segue dentro do prazo, conforme planejado\r\nEdital  publicado - provas 01/11/2026\r\nMaterial de treinamento em elaboração",
      "Período da última semana": "28/09/2026 a 02/10/2035",
      "O que foi feito na última semana": "Alinhamento com as áreas de negócio sobre o conteúdo programático",
      "% Execução": "15",
      "Data Início": "46210",
      "Data Fim Planejada": "46461",
      "Data Fim Atual": "46461",
      "Data Última RAP": "45915",
      "Últimas Atualizações": "Publicação do Edital - prova 01/11/2026\r\nRealizada orientação para as sobre como preencher templates de treinamento\r\nRealizado alinhamento com DHC sobre aquisição e disponibilização dos tablets",
      "Próximos Passos": "Realizar alinhamento de atividades com DHC e DTI\r\nRealizar alinhamento de atividades e cronograma com Assessoria da Presidência",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "Atraso na revisão e validação do conteúdo da capacitação.\r\nAlteralçao do conteúdo durante a etapa de ambientação no AVA\r\nAlterações normativas durante a produção do conteúdo da capacitação",
      "Escopo": "Realizar concurso público para contratação de novos Agentes Estaduais de Transito.\r\nPromover a recepção dos novos agentes, garantindo que o processo de onboarding seja estruturado e acolhedor.\r\nA iniciativa contempla a apresentação institucional, incluindo áreas da empresa, benefícios e regras internas, além de reforçar a integração cultural por meio de atividades que transmitam valores, missão e visão da organização, serão ministrados treinamentos operacionais voltados às rotinas e processos específicos de cada função, com suporte de ferramentas digitais que centralizam informações, documentos e conteúdos de capacitação.",
      "Objetivos Estratégicos": "Aperfeiçoar a estrutura organizacional e a qualificação do atendimento\r\nOtimizar a gestão de pessoas e adequar a força de trabalho\r\nDesenvolver competências convergentes com a estratégia institucional\r\nAprimorar a educação corporativa e para o trânsito\r\nOtimizar a experiência e a satisfação do usuário com o atendimento\r\n\r\n",
      "% Consumo Prazo": "36"
    },
    {
      "ID Projeto": "PRJ011",
      "Projeto": "ESTRATÉGIA DETRAN-SP",
      "Portaria": "Portaria Normativa DETRAN-SP nº 6, de 31 de agosto de 2023",
      "GP": "",
      "Área": "Presidência",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2036",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Contempla o mapa estratégico, cadeia de valor, portfólio de projetos estratégicos, portfólio de indicadores estratégicos e carta de serviços",
      "Objetivos Estratégicos": "Implementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nDisseminar a cultura de inovação, a gestão de projetos e processos\r\nImplementar gestão de performance e subsidiar as decisões com evidências\r\nOtimizar a experiência e a satisfação do usuário com o atendimento\r\nAdotar o modelo de governança multinível em rede"
    },
    {
      "ID Projeto": "PRJ012",
      "Projeto": "GUILHOTINA REGULATÓRIA",
      "Portaria": "Portaria Normativa DETRAN-SP nº 1, de 20 de março de 2023",
      "GP": "",
      "Área": "DGR",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2037",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": " Definir a forma de como se publica portarias, revogar uma série de portarias e enxugar as novas portarias.",
      "Objetivos Estratégicos": "Simplificar a gestão regulatória e induzir avanços nas normas de trânsito\r\nReduzir o custo dos serviços e contribuir para a competitividade e a prosperidade do Estado de São Paulo"
    },
    {
      "ID Projeto": "PRJ013",
      "Projeto": "MARCA DO DETRAN-SP",
      "Portaria": "Portaria Normativa DETRAN-SP nº 3, de 20 de julho de 2023",
      "GP": "",
      "Área": "Presidência",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2038",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Construção da marca do Detran-SP.\r\nTransmitir ao cidadão a eficiência e a confiança nos serviços.\r\nTransmitir o conceito disponibilidade do Detran-SP em atender o cidadão.\r\n",
      "Objetivos Estratégicos": "Comunicar com foco nos serviços, na prestação de contas e na construção da marca\r\nAssegurar a qualidade dos serviços delegados com foco na excelência operacional\r\nOtimizar a experiência e a satisfação do usuário com o atendimento\r\nAmpliar a disponibilidade, a eficiência e a acessibilidade digital de todos os serviços a todas as pessoas"
    },
    {
      "ID Projeto": "PRJ014",
      "Projeto": "BONIFICAÇÃO POR RESULTADOS",
      "Portaria": "LEI COMPLEMENTAR N° 1.361, DE 21 DE OUTUBRO DE 2021",
      "GP": "",
      "Área": "Presidência",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2039",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Implementar a bonificação por resultados no DETRAN-SP, nos termos da LEI COMPLEMENTAR N° 1.361, DE 21 DE OUTUBRO DE 2021.\r\n",
      "Objetivos Estratégicos": "Desenvolver competências convergentes com a estratégia institucional\r\nCuidar das pessoas e valorizar o desempenho e o mérito\r\nAprimorar a educação corporativa e para o trânsito\r\nImplantar mecanismos de gestão meritocrática e promover o espírito de equipe\r\nImplementar gestão de performance e subsidiar as decisões com evidências\r\nDisseminar a cultura de inovação, a gestão de projetos e processos\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nOtimizar a experiência e a satisfação do usuário com o atendimento\r\nSubsidiar políticas públicas com foco em resultados concretos e mensuráveis"
    },
    {
      "ID Projeto": "PRJ015",
      "Projeto": "WIKI",
      "Portaria": "",
      "GP": "",
      "Área": "AEGE",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2040",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Criar uma plataforma de conhecimento para o Detran-SP, permitindo que os colaboradores de todas as áreas possam acessar, compartilhar e atualizar informações essenciais de forma prática e ágil. ",
      "Objetivos Estratégicos": "Implementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nDisseminar a cultura de inovação, a gestão de projetos e processos\r\nImplantar mecanismos de gestão meritocrática e promover o espírito de equipe\r\nEmpregar soluções tecnológicas inovadoras para alavancar os resultados"
    },
    {
      "ID Projeto": "PRJ016",
      "Projeto": "HEIMDALL",
      "Portaria": "",
      "GP": "",
      "Área": "DTI",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2041",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Contratação direta da Companhia de Processamento de Dados do Estado de São Paulo – PRODESP para prestação de Serviços de Segurança de Identidade em TI (Tecnologia da Informação) composto de:\r\nServiço de Proteção e Gerenciamento de Identidades Privilegiadas (Privilegie Access Management - PAM);\r\nO serviço de proteção e gerenciamento de identidades privilegiadas tem como objetivo proteger as contas privilegiadas através da descoberta e troca periódica de senhas/contas.\r\nServiço de Proteção e Gerenciamento de Privilégios de Estações de Trabalho (Enterprise Performance Management - EPM);\r\nO serviço de proteção e gerenciamento de privilégios de estações de trabalho tem como objetivo proteger endpoints contra-ataques, reduzindo o risco de informações serem roubadas ou criptografadas, como um ataque ransomware, além da prevenção de roubo de credenciais, realizar o bloqueio de instalações de aplicações não autorizadas e elevação de privilégios.\r\nServiço de Proteção e Gerenciamento de Usuários de Negócio (Identity and Access Management - IAM) e;\r\nO serviço de Gerenciamento de Usuários de Negócio fornece uma plataforma unificada para a centralização dos logins dos usuários, bem como Múltiplos Fatores de Autenticação para proteger os acessos às aplicações de negócio.\r\nServiço de Proteção e Gerenciamento de Identidades Privilegiadas não Humanas.\r\nO serviço de proteção de identidades de aplicações modernas é capaz de gerenciar e rotacionar credenciais de aplicações em contêineres, entregando as credenciais para suas aplicações diretamente na esteira de desenvolvimento.\r\nO serviço se adequa a disciplina de proteção e gerenciamento de identidades privilegiadas, capaz de remover credenciais embutidas em código e garantir o conceito de menor privilégio.",
      "Objetivos Estratégicos": "Promover a cultura de integridade e auditoria permanente, combatendo com agilidade os desvios e a corrupção\r\nEstruturar o controle interno e a gestão de riscos com as melhores práticas de compliance\r\nGarantir a segurança, integridade e efetiva governança de dados e informações"
    },
    {
      "ID Projeto": "PRJ017",
      "Projeto": "LGPD",
      "Portaria": "",
      "GP": "",
      "Área": "DTI",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2042",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "O projeto tem por finalidade a implantação no âmbito do DETRAN-SP, dos dispositivos estabelecidos pela Lei Geral de Proteção de Dados, envolvendo todas as operações que possuam tratamento de dados pessoais no setor de Atendimento ao Cliente e domínio do site DETRAN-SP.\r\nTem por finalidade, ainda, mapear os processos internos, estabelecer o plano de riscos e falhas, editar e/ou revisar políticas de privacidade, termos de privacidade, contratos e procedimentos operacionais e administrativos, bem como promover a conscientização dentro da autarquia sobre referida lei e boas práticas, visando garantir a total adesão à LGPD.\r\nAo final do projeto, estima-se que o DETRAN-SP conte com os seguintes resultados:\r\n\r\nPolítica de Privacidade do Site.\r\nPolítica de Privacidade de Cookies.\r\nPolíticas de Privacidade Institucionais.\r\nPrograma Corporativo de Conscientização sobre à LGPD.\r\nTreinamento.\r\nEstruturação do Comitê de Privacidade\r\nMapeamento de Dados Pessoais (Data Mapping) do Site e Atendimento ao Cliente.\r\nGap Analysis do Site e Atendimento ao Cliente.\r\nRecord Of Processing Activities (ROPA) inicial.\r\nRelatório de Impacto a Proteção de Dados (RIPD).\r\nControle de Evidências.\r\nAdequação de aditivos contratuais.\r\nTermos de privacidade.\r\nDue Diligence.\r\nPrivacy by Design.\r\nPlano de Resposta a Incidentes de Segurança.\r\nCriação do Controle de solicitações e resposta a titulares de dados.\r\nCriação do Processo de Sustentação ao Programa de Privacidade",
      "Objetivos Estratégicos": "Adotar as melhores práticas de transparência ativa, de acesso à informação e de proteção de dados\r\nGarantir a segurança, integridade e efetiva governança de dados e informações\r\nEstruturar o controle interno e a gestão de riscos com as melhores práticas de compliance"
    },
    {
      "ID Projeto": "PRJ018",
      "Projeto": "SUPERNOVA",
      "Portaria": "Portaria DETRAN-SP nº 3.481, de 23 de maio de 2024",
      "GP": "",
      "Área": "DAC",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2043",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Planejar, implementar e gerir a equipe de fornecedores para desenvolvimento do novo portal de serviços ao cidadão e do aplicativo móvel.",
      "Objetivos Estratégicos": "Otimizar a experiência e a satisfação do usuário com o atendimento\r\nAmpliar a disponibilidade, a eficiência e a acessibilidade digital de todos os serviços a todas as pessoas\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nComunicar com foco nos serviços, na prestação de contas e na construção da marca\r\nAdotar as melhores práticas de transparência ativa, acesso à informação e proteção de dados\r\nSer a plataforma de integração, informação e cooperação para o trânsito\r\nEmpregar soluções tecnológicas inovadoras para alavancar os resultados"
    },
    {
      "ID Projeto": "PRJ019",
      "Projeto": "CSM",
      "Portaria": "Portaria DETRAN-SP nº 4.021, de 13 de junho de 2024",
      "GP": "",
      "Área": "DTI",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2044",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "FASE 1 - Implementação do Serviço de Atendimento ao Cidadão (SAC), destinado ao tratamento das manifestações dos cidadãos.\r\nDesenvolvimento do Portal SAC com integração GOV.br\r\nGovernança na gestão de contas.\r\nGovernança na gestão da retaguarda (grupos e assuntos).\r\nDesenvolvimento de API para governança de dados.\r\nFASE 2 - Provimento de serviços aos usuários externos, bem como de serviços internos para as diretorias do Departamento Estadual de Trânsito de São Paulo (DETRAN-SP).\r\n\r\nDesenvolvimento do módulo serviços.\r\nDesenvolvimento da integração ao SEI.\r\nIntegração com a Intranet.\r\nDesenvolvimento da TI para governança de dados.\r\nDisponibilização dos serviços de forma responsiva no novo APP Detran.",
      "Objetivos Estratégicos": "Otimizar a experiência e a satisfação do usuário com o atendimento\r\nAmpliar a disponibilidade, a eficiência e a acessibilidade digital de todos os serviços a todas as pessoas\r\nAutomatizar os processos com emprego de inteligência artificial e aprendizagem de máquinas\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nImplementar gestão de performance e subsidiar as decisões com evidências\r\nAdotar as melhores práticas de transparência ativa, acesso à informação e proteção de dados\r\nEmpregar soluções tecnológicas inovadoras para alavancar resultados\r\nAperfeiçoar a estrutura organizacional e a qualificação do atendimento"
    },
    {
      "ID Projeto": "PRJ020",
      "Projeto": "#SOUDETRAN",
      "Portaria": "",
      "GP": "",
      "Área": "ASCOM",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2045",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Desenvolvimento e implementação de um ambiente de trabalho digital (digital workplace) para os colaboradores do Detran-SP, consolidando em uma única plataforma as informações e ferramentas necessárias para o seu dia a dia, desde o onboarding até a aposentadoria.\r\nEsta solução estará alinhada com a essência do employee experience, visando aumentar o engajamento dos colaboradores através de funcionalidades que promovam a comunicação e transparência, a colaboração, o aprendizado e a produtividade.\r\nA solução tecnológica será integrada ao ecossistema da Microsoft, podendo ser acessada via Teams e contará com três subprodutos principais:\r\n\r\nIntranet (#SouDetranSP) – Microsoft Viva Connections: Portal interno com ênfase na organização, produtividade, comunicação institucional, interação e gestão de pessoas (praVC).\r\nSerá o principal ponto de acesso para o colaborador obter informações institucionais, atualizações e encontrar as ferramentas necessárias para a execução de suas tarefas.\r\nRede Social Corporativa – Microsoft Viva Engage: Ferramenta dedicada a promover a comunicação ágil com e entre os colaboradores, incentivando a colaboração e troca de conhecimentos.\r\nPermitirá a criação de comunidades baseadas em processos de negócio, possibilitando uma coleta de informações bottom-up, o que contribuirá para a melhoria contínua dos processos internos.",
      "Objetivos Estratégicos": "Otimizar a gestão de pessoas e adequar a força de trabalho\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nImplantar mecanismos de gestão meritocrática e promover o espírito de equipe\r\n"
    },
    {
      "ID Projeto": "PRJ021",
      "Projeto": "REFORMA ADMINISTRATIVA",
      "Portaria": "DECRETO N° 69.053, DE 14 DE NOVEMBRO DE 2024",
      "GP": "",
      "Área": "Presidência",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2046",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Aprovar a Estrutura Organizacional e o Quadro Demonstrativo dos Cargos em Comissão e das Funções de Confiança do Departamento Estadual de Trânsito - DETRAN-SP.",
      "Objetivos Estratégicos": "Adotar o modelo de governança multinível em rede"
    },
    {
      "ID Projeto": "PRJ022",
      "Projeto": "LIVE",
      "Portaria": "Portaria DETRAN-SP nº 5.561, de 20 de setembro de 2024",
      "GP": "",
      "Área": "DCA",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2047",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Criar aplicativo parta a liberação imediada de veículo recolhido, mediante o pagamento de todas as taxas recolhido ",
      "Objetivos Estratégicos": "Automatizar os processos com emprego de inteligência artificial e aprendizagem de máquinas\r\nAmpliar a disponibilidade, a eficiência e a acessibilidade de todos os serviços a todas as pessoas \r\nOtimizar a experiência e a satisfação do usuário com o atendimento\r\nAssegurar a qualidade dos serviços delegados com foco na excelência operacional\r\nReduzir o custo dos serviços e contribuir para a competitividade e a prosperidade do Estado de São Paulo"
    },
    {
      "ID Projeto": "PRJ023",
      "Projeto": "ARQUITETURA DE TIC",
      "Portaria": "",
      "GP": "Sérgio Araújo",
      "Área": "DTI",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2048",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Dar visibilidade a todos os aspectos que compõem o parque tecnológico, incluindo a compreensão de todo investimento ativo e recorrente, sua disponibilidade, duplicidades, efetividade e eficiência operacional, assim como identificar e avaliar a necessidade e manutenção, mirando a melhoria contínua.\r\nAinda, atualizar o desenho da topologia dos sistemas, destacando todas as suas conexões e integrações, possíveis pontos de melhorias e recomendações, e preparação dos ambientes para mudança.\r\nPriorizar os sistemas estratégicos para tomada de decisão quanto a investimento, aposentadoria de sistemas, convivência e reestruturação.\r\nO projeto engloba o mapeamento de todos os componentes do Detran-SP e interfaces que compõem a arquitetura dos sistemas, considerando, mas não se limitando, aos seguintes aspectos:",
      "Objetivos Estratégicos": "Empregar soluções tecnológicas inovadoras para alavancar os resultados\r\nGarantir a segurança, integridade e efetiva governança de dados e informações\r\nOtimizar a alocação e modernização dos equipamentos e da infraestrutura\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade\r\nImplementar gestão de performance e subsidiar as decisões com evidências\r\nAdotar as melhores práticas de transparência ativa, acesso à informação e proteção de dados\r\nEstruturar o controle interno e a gestão de riscos com as melhores práticas de compliance\r\nReduzir o custo dos serviços e contribuir para a competitividade e a prosperidade do Estado de São Paulo"
    },
    {
      "ID Projeto": "PRJ024",
      "Projeto": "INFOSIGA",
      "Portaria": "",
      "GP": "",
      "Área": "DSV",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2049",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Melhorar a qualidade dos dados por meio da aplicação de inteligência artificial, ampliar a capacidade de georreferenciamentodos sinistros, com uso de metodologias baseadas em CadLoge APIs, integrar dados externos estratégicos, implementar alertas gerenciais e enriquecimento de painéis com indicadores críticos, favorecendo a tomada de decisão e o monitoramento contínuo dos dados e aprimoramento da interface como usuário por meio de alterações no front-end.",
      "Objetivos Estratégicos": "Promover a segurança no trânsito e reduzir os indicadores de óbitos e feridos em sinistros\r\nSubsidiar políticas públicas com foco em resultados concretos e mensuráveis\r\nSer a plataforma de integração, informação e cooperação para o trânsito"
    },
    {
      "ID Projeto": "PRJ025",
      "Projeto": "TDV",
      "Portaria": "Portaria DETRAN-SP nº 5.561, de 20 de setembro de 2024",
      "GP": "",
      "Área": "DVA",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2050",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Implementar a transferência de propriedade de veículos de forma digital através do aplicativo CDT (Carteira Digital de Trânsito)",
      "Objetivos Estratégicos": "Otimizar a experiência e a satisfação do usuário com o atendimento\r\nReduzir o custo dos serviços e contribuir para a competitividade e a prosperidade do Estado de São Paulo\r\nAutomatizar os processos com emprego de inteligência artificial e aprendizagem de máquinas\r\nImplementar as melhores práticas para a excelência dos processos internos e serviços à sociedade"
    },
    {
      "ID Projeto": "PRJ026",
      "Projeto": "WS ROTA DOS EXAMINADORES",
      "Portaria": "",
      "GP": "",
      "Área": "DHC",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2051",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Realizar um workshop para reciclagem dos examinadores, com oficinas teóricas e práticas sobre o exame pratico de direção.\r\nPadronizar o exame em todo o estado.\r\nCriar um novo manual do exame prático.",
      "Objetivos Estratégicos": "Aperfeiçoar a estrutura organizacional e a qualificação do atendimento\r\nDesenvolver competências convergentes com a estratégia institucional\r\nOtimizar a experiência e a satisfação do usuário com o atendimento\r\nOtimizar a fiscalização com foco na promoção da segurança e da eficiência\r\nPromover a segurança no trânsito e reduzir os indicadores de óbitos e feridos em sinistros\r\nAprimorar a educação corporativa e para o trânsito"
    },
    {
      "ID Projeto": "PRJ027",
      "Projeto": "DETRAN PAY",
      "Portaria": "Portaria DETRAN-SP nº 5.561, de 20 de setembro de 2024",
      "GP": "",
      "Área": "DAL",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2052",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "A Plataforma Detran-Pay é a solução institucional responsável por gerar, processar e validar\r\npagamentos oficiais, habilitar a execução de serviços, controlar o ciclo de vida da vistoria e\r\nrealizar a distribuição financeira dos valores arrecadados entre os entes envolvidos no processo.\r\nA plataforma atua como núcleo financeiro e operacional, integrando cidadãos, meios de pagamento, Backoffice Operacional, Empresas Credenciadas de Vistoria (ECVs), Integradoras e Auditoras, garantindo que todo serviço executado esteja formalmente vinculado a um pagamento válido, conciliado e distribuído conforme regras institucionais.\r\nO Detran-Pay é responsável por:\r\n● gerar o QRCode de pagamento do serviço\r\n● processar e confirmar o pagamento\r\n● gerar o token de vistoria somente após confirmação financeira\r\n● controlar os status da vistoria em comunicação direta com o Backoffice Operacional\r\n● receber o encerramento da vistoria\r\n● realizar a distribuição financeira do valor total da vistoria entre:  ECV, Integradora e  Auditora\r\n● encaminhar a parcela institucional do Detran-SP por meio de pagamento via DARE\r\n● disponibilizar consulta de pagamentos para o Portal dos Credenciados\r\n● manter serviço de cadastro, atualização e consulta de dados bancários das entidades credenciadas\r\n● disponibilizar extrato de pagamentos ao cidadão autenticado\r\n● receber e registrar pedidos de restituição.\r\n",
      "Objetivos Estratégicos": "Assegurar a qualidade dos serviços delegados com foco na excelência operacional\r\nAprimorar a gestão de receitas e a aplicação de recursos orçamentários e financeiros"
    },
    {
      "ID Projeto": "PRJ028",
      "Projeto": "WS ROTA SEGURA",
      "Portaria": "",
      "GP": "",
      "Área": "DFT",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2053",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Realizar o primeiro workshop com aulas teóricas e oficinas práticas para formação de público docentes e discentes de agentes de trânsito ativos/aptos para exercer a função de fiscalização de trânsito.\r\nA Diretoria de Fiscalização de Trânsito de forma inédita, junto com a EPT, formará seus próprios agentes de Fiscalização de trânsito para que atuem com foco na educação e segurança no trânsito em suas abordagens, juntamente com o apoio da PM.",
      "Objetivos Estratégicos": "Otimizar a fiscalização com foco na promoção da segurança e da eficiência\r\nPromover a segurança no trânsito e reduzir os indicadores de óbitos e feridos em sinistros\r\nOtimizar a experiência e a satisfação do usuário com o atendimento\r\nAperfeiçoar a estrutura organizacional e a qualificação do atendimento\r\nDesenvolver competências convergentes com a estratégia institucional\r\nAprimorar a educação corporativa e para o trânsito"
    },
    {
      "ID Projeto": "PRJ029",
      "Projeto": "NORMAS",
      "Portaria": "Portaria DETRAN-SP nº 5.561, de 20 de setembro de 2024",
      "GP": "",
      "Área": "DGR",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2054",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Criação de um framework para estruturar a gestão e governança normativa do Estado de São Paulo, por meio de uma curadoria automatizada e centralizada, com o objetivo de realizar o gerenciamento do arcabouço legislativo do Estado, abrangendo o ciclo de vida da norma, no tempo e no espaço e garantindo a fidelidade dos dados ao longo do tempo.",
      "Objetivos Estratégicos": "Simplificar a gestão regulatória e indizir avanços nas normas de trânsito\r\nAutomatizar os processos com emprego de inteligência artificial e aprendizagem de máquinas\r\nReduzir o custo dos serviços e contribuir para a competitividade e a prosperidade do Estado de São Paulo\r\nSer a plataforma de integração, informação e cooperação para o trânsito"
    },
    {
      "ID Projeto": "PRJ030",
      "Projeto": "SISTEMA ESTADUAL DO TRÂNSITO",
      "Portaria": "DECRETO N° 68.347, DE 29 DE FEVEREIRO DE 2024",
      "GP": "",
      "Área": "DSV",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2055",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": " Instituir o Sistema Estadual de Trânsito - SISTRAN-SP, com o objetivo de promover, no âmbito do Estado de São Paulo, a integração e a cooperação dos órgãos e entidades integrantes do Sistema Nacional de Trânsito - SNT, assegurando, entre esses, atuação uniforme, harmônica e coordenada.",
      "Objetivos Estratégicos": "Estruturar o Sistema Estadual de Trânsito\r\nFortalecer a atuação e a cooperação com os demais órgãos de trânsito e segurança pública\r\nSer a plataforma de integração, informação e cooperação para o trânsito\r\nImplementar rede colaborativa de parceiros em prol da segurança de todos\r\n"
    },
    {
      "ID Projeto": "PRJ031",
      "Projeto": "PROGRAMA DE INTEGRIDADE",
      "Portaria": "Portaria Normativa DETRAN-SP nº 21, de 1º de março de 2024",
      "GP": "",
      "Área": "DCI",
      "Status": "Concluído",
      "Situação": "Concluído",
      "Justificativa da Situação": "",
      "Período da última semana": "28/09/2026 a 02/10/2056",
      "O que foi feito na última semana": "",
      "% Execução": "100",
      "Data Início": "",
      "Data Fim Planejada": "",
      "Data Fim Atual": "",
      "Data Última RAP": "",
      "Últimas Atualizações": "",
      "Próximos Passos": "",
      "Pontos de Atenção": "",
      "Impedimentos": "",
      "Pendências": "",
      "Riscos": "",
      "Escopo": "Implementar o Programa de Integridade, que consiste em um conjunto estuturado de ações e medidas institucionais para prevenção, detecção e punição de práticas de corrupção, de fraude, de desvios éticos e de outros ilícitos.",
      "Objetivos Estratégicos": "Otimizar a experiência e a satisfação do usuário com o atendimento\r\nEstruturar o controle interno e a gestão de riscos com as melhores práticas de compliance\r\nPromover a cultura de integridade e auditoria permanente, combatendo com agilidade os desvios e a corrupção\r\nComunicar com foco nos serviços, na prestação de contas e na construção da marca\r\nAdotar as melhores práticas de transparência ativa, acesso à informação e proteção de dados"
    }
  ]
};
